import edu.rit.ds.RemoteEvent;

/**
 * Class MicroblogEvent encapsulates a remote event generated by a microblog 
 * in the P2Patter system. The microblog events are used to report addMessage 
 * activity to the follow programs.
 */
public class MicroblogEvent 
	extends RemoteEvent
	{
	public final String name;
	public final AddMessage message;
	
	/**
	 * Create a new microblog event.
	 *
	 * @param	name	 Microblog owner name.
	 * @param	message  AddMessage object that was received.
	 */
	public MicroblogEvent
		(String name,
		 AddMessage message)
		{
		this.name = name;
		this.message = message;
		}
	}
